### PR TITLE
Add liuggio/fastest for #11.

### PR DESCRIPTION
**Pull request by michaelhagedon**
Add this parallelization library for https://github.com/az-digital/az_quickstart/issues/507.

### CODE REVIEW

**Comment by michaelhagedon** [comment]
OK, I've added the repo and maybe this is ready for review now.

**Review by joeparsons — APPROVED** [review]

**Comment by joeparsons** [comment]
I'm tempted to merge this right away to clear the way for az-digital/az_quickstart/pull/635.  Any concerns with that @tadean, @mmunro-ltrr, @trackleft ?  (see discussion in #11).

**Review by mmunro-ltrr — DISMISSED** [review]
In the interests of keeping this moving along!

**Comment by tadean** [comment]
Should the version of `liuggio/fastest` be pinned to a specific version like the other dependencies? Currently it is `^1.7`

**Comment by joeparsons** [comment]
> Should the version of `liuggio/fastest` be pinned to a specific version like the other dependencies? Currently it is `^1.7`

Oh, yes.  Good catch.  @michaelhagedon We've been pinning our dependencies to specific versions to try to have more deterministic builds (without committing lock files).

**Review by trackleft — DISMISSED** [review]

**Comment by michaelhagedon** [comment]
> > Should the version of `liuggio/fastest` be pinned to a specific version like the other dependencies? Currently it is `^1.7`
> 
> Oh, yes. Good catch. @michaelhagedon We've been pinning our dependencies to specific versions to try to have more deterministic builds (without committing lock files).

Oh, good call! I've done that now.

**Review by mmunro-ltrr — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
